// Copyright (c) 2026 Geramy Loveless DBA Nexus Projects.
// Author: Geramy Loveless <support@nexus-projects.ai>
// Licensed under the Sustainable Use License. See LICENSE.md.

/// Generates the per-app SCREEN-MAP HARNESS: a `flutter test` file that pumps
/// the generated app, visits each route, and captures — per screen — a PNG of
/// what actually renders plus a REGIONS list (which widget is at which pixel,
/// from which source line, via the debug creation stack). The file is written
/// into the MATERIALIZED copy only and deleted afterwards; the project's
/// committed workspace is never touched.
library;

/// One named route to visit (in order). '' = the app's home, always first.
class HarnessRoute {
  const HarnessRoute(this.name, this.label);
  final String name; // the route key, e.g. /task-56-…
  final String label; // short rail name
}

/// Build the harness test source.
///
/// [outDir] is the host directory where PNGs + screens.json are written.
String generateHarnessTest({
  required String packageName,
  required List<HarnessRoute> routes,
  required String outDir,
}) {
  final routesBlock = routes
      .map((r) =>
          "    HarnessRoute('${_esc(r.name)}', '${_esc(r.label)}'),")
      .join('\n');

  return '''
// GENERATED by Nexus Studio — Visual Editor screen-map harness.
// Runs once per capture, then is deleted. Never commit this file.
import 'dart:convert';
import 'dart:io';
import 'dart:ui' as ui;

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:$packageName/main.dart' as app;

class HarnessRoute {
  const HarnessRoute(this.name, this.label);
  final String name;
  final String label;
}

const String _outDir = r'$outDir';

const List<HarnessRoute> _routes = [
$routesBlock
];

Future<void> main() async {
  TestWidgetsFlutterBinding.ensureInitialized();
  testWidgets('nexus screen map', (tester) async {
    tester.view.physicalSize = const Size(1280, 800);
    tester.view.devicePixelRatio = 1.0;
    addTearDown(tester.view.resetPhysicalSize);
    addTearDown(tester.view.resetDevicePixelRatio);
    await tester.runAsync(() async {
      Directory(_outDir).createSync(recursive: true);
      await _loadTestFonts();
    });
    _mockCommonPlugins();
    try {
      app.main();
    } catch (e) {
      debugPrint('harness: app.main() threw: \$e');
    }
    // Bounded settle — apps with endless animations must not hang us.
    for (var i = 0; i < 20; i++) {
      await tester.pump(const Duration(milliseconds: 120));
      tester.takeException(); // drain — see per-route loop
    }
    final screens = <Map<String, dynamic>>[];
    var idx = 0;
    for (final route in _routes) {
      idx++;
      final label = route.label.isEmpty ? 'home' : route.label;
      final pngName = 's\${idx.toString().padLeft(2, '0')}_\${_slug(label)}.png';
      try {
        if (route.name.isNotEmpty) {
          final nav = _navigator(tester);
          if (nav == null) {
            screens.add(_errScreen(route, 'no Navigator found'));
            continue;
          }
          // REPLACE, don't push: a plain pushNamed leaves the previous route
          // painted *beneath* the new one in the render tree, and the region
          // walk below would then capture the hidden screen (e.g. a home
          // route-list) instead of the visible one. Replacing makes each screen
          // the only route, so the captured regions match what's on screen.
          nav.pushReplacementNamed(route.name);
        }
        // Pump; DRAIN exceptions every frame. The app under capture may have
        // real layout/render bugs (thrown every frame) — we record them on
        // the screen and keep going; we never fail the capture over them.
        String? exception;
        for (var i = 0; i < 25; i++) {
          await tester.pump(const Duration(milliseconds: 120));
          final ex = tester.takeException();
          if (ex != null) exception = ex.toString().split('\\n').first;
        }
        // Rasterization is real async — it must run in a real-async zone or
        // the fake-async test zone deadlocks (the classic golden-test hang).
        final img = await tester.runAsync(() async {
          final layer = tester.binding.renderView.debugLayer!;
          if (layer is! OffsetLayer) {
            throw StateError(
                'unsupported root layer type \${layer.runtimeType}');
          }
          return layer.toImage(tester.binding.renderView.paintBounds);
        });
        final bytes = (await tester.runAsync(
                () async => (await img!.toByteData(
                            format: ui.ImageByteFormat.png))!
                        .buffer
                        .asUint8List()))!;
        // Raw RGBA for per-region pixel sampling — this is how we learn the
        // ACTUAL painted background of each region (AppBar, ColoredBox,
        // Container, buttons, …) regardless of which widget painted it.
        final raw = (await tester.runAsync(
                () async => (await img!.toByteData(
                            format: ui.ImageByteFormat.rawRgba))!
                        .buffer
                        .asUint8List()))!;
        await tester.runAsync(() async {
          await File('\$_outDir/\$pngName').writeAsBytes(bytes);
        });
        final w = tester.view.physicalSize!.width ~/
            tester.view.devicePixelRatio;
        final h = tester.view.physicalSize!.height ~/
            tester.view.devicePixelRatio;
        final regions = _regions(tester, 's\$idx', raw, w, h);
        screens.add({
          'route': route.name,
          'label': label,
          'png': pngName,
          'w': w,
          'h': h,
          if (exception != null) 'error': 'rendered with: \$exception',
          'regions': regions,
        });
      } catch (e) {
        screens.add(_errScreen(route, '\$e'));
      }
    }
    // Drain any final pending exceptions so the test framework never fails
    // the capture over app-side render bugs.
    Object? leftover;
    while ((leftover = tester.takeException()) != null) {}
    await tester.runAsync(() async {
      await File('\$_outDir/screens.json')
          .writeAsString(jsonEncode(screens));
    });
    debugPrint('NEXUS_SCREEN_MAP_DONE \${screens.length}');
  }, timeout: const Timeout(Duration(minutes: 6)));
}

Map<String, dynamic> _errScreen(HarnessRoute route, String err) => {
      'route': route.name,
      'label': route.label.isEmpty ? 'home' : route.label,
      'png': '',
      'w': 0,
      'h': 0,
      'error': err,
      'regions': <Map<String, dynamic>>[],
    };

/// Load real fonts before pumping: the test environment renders text with
/// the Ahem font (uniform black squares) unless real font data is loaded for
/// the family it resolves to. In this SDK the default test family is
/// 'monospace', so Roboto is loaded under that name (verified: distinct
/// pixel count 98 → 246) as well as under 'Roboto' and 'Ahem' for safety,
/// and MaterialIcons so icons aren't boxes either.
Future<void> _loadTestFonts() async {
  final root = Platform.environment['FLUTTER_ROOT'];
  if (root == null) return;
  final dir = '\$root/bin/cache/artifacts/material_fonts';
  const faces = [
    'Roboto-Regular.ttf',
    'Roboto-Bold.ttf',
    'Roboto-Italic.ttf',
    'Roboto-BoldItalic.ttf',
  ];
  for (final file in faces) {
    final f = File('\$dir/\$file');
    if (!await f.exists()) continue;
    final bytes = f.readAsBytesSync();
    for (final family in const ['monospace', 'Roboto', 'Ahem']) {
      final loader = FontLoader(family)
        ..addFont(Future.value(ByteData.view(bytes.buffer)));
      await loader.load();
    }
  }
  final icons = File('\$dir/MaterialIcons-Regular.otf');
  if (await icons.exists()) {
    final loader = FontLoader('MaterialIcons')
      ..addFont(Future.value(ByteData.view(icons.readAsBytesSync().buffer)));
    await loader.load();
  }
}

NavigatorState? _navigator(WidgetTester tester) {
  try {
    return tester.state<NavigatorState>(find.byType(Navigator).first);
  } catch (_) {
    return null;
  }
}

/// First non-empty rendered text in [e]'s render subtree (bounded) — the
/// label a card/button/header shows. Null if the subtree has no text.
String? _firstDescendantText(Element e) {
  String? found;
  var visited = 0;
  void walk(Element el) {
    if (found != null || visited > 60) return;
    visited++;
    final ro = el.renderObject;
    if (ro is RenderParagraph) {
      final t = ro.text.toPlainText().trim();
      if (t.isNotEmpty) {
        found = t.length > 60 ? t.substring(0, 60) : t;
        return;
      }
    }
    el.visitChildElements(walk);
  }

  e.visitChildElements(walk);
  return found;
}

/// Walk the element tree and record every meaningful RenderBox as a region:
/// type, on-screen rect, rendered TEXT (for RenderParagraph), TEXT COLOR
/// (glyph style), the painted BACKGROUND COLOR (sampled from the raster,
/// with a RenderDecoratedBox solid fill as an exact fallback), and the WIDGET
/// CHAIN (runtime type names up the parent chain) — the Studio uses those to
/// reverse-map the region to a source file:line (text literals and exact color
/// values are greppable in the app's code).
List<Map<String, dynamic>> _regions(
    WidgetTester tester, String screenId, List<int> raw, int w, int h) {
  final out = <Map<String, dynamic>>[];
  final root = tester.binding.rootElement;
  if (root == null) return out;
  var n = 0;
  void visit(Element e, int depth) {
    if (n >= 500) return;
    final ro = e.renderObject;
    if (ro is RenderBox && ro.attached) {
      final size = ro.size;
      if (size.width >= 8 &&
          size.height >= 8 &&
          size.width <= 4000 &&
          size.height <= 4000) {
        String? text;
        String? textColor;
        if (ro is RenderParagraph) {
          text = ro.text.toPlainText().trim();
          if (text.length > 80) text = text.substring(0, 80);
          if (text.isEmpty) text = null;
          final tc = ro.text.style?.color;
          if (tc != null) textColor = _hex(tc);
        }
        final type = ro.runtimeType.toString();
        final tl = ro.localToGlobal(Offset.zero);
        // Painted background: sample the actual pixels (captures backgrounds
        // from AppBar/ColoredBox/Container/buttons/any widget). A solid
        // RenderDecoratedBox fill is used verbatim when present (exact).
        String? color = _modeColor(raw, w, h, tl.dx, tl.dy, size.width, size.height);
        if (ro is RenderDecoratedBox) {
          final d = ro.decoration;
          if (d is BoxDecoration && d.color != null) {
            color = _hex(d.color!);
          }
        }
        // For non-text regions (cards, buttons, headers) record the first
        // descendant text — a strong anchor the Studio greps to find this
        // widget's source, since a repeated background colour alone is
        // ambiguous.
        String? childText;
        if (ro is! RenderParagraph) {
          childText = _firstDescendantText(e);
        }
        final chain = <String>[];
        e.visitAncestorElements((anc) {
          final t = anc.widget.runtimeType.toString();
          if (t.isNotEmpty && !chain.contains(t)) chain.add(t);
          return chain.length < 5;
        });
        final n2 = out.length;
        out.add({
          'id': '\$screenId-\${n2.toString().padLeft(3, '0')}',
          't': type,
          'label': _labelFor(type),
          if (text != null) 'text': text,
          if (textColor != null) 'textColor': textColor,
          if (color != null) 'color': color,
          if (childText != null) 'childText': childText,
          'chain': chain,
          'r': {
            'x': tl.dx,
            'y': tl.dy,
            'w': size.width,
            'h': size.height,
          },
          'd': depth,
        });
        n++;
      }
    }
    if (n < 500) {
      e.visitChildElements((c) => visit(c, depth + 1));
    }
  }

  visit(root, 0);
  // Dedupe: when two regions share the same rect, keep the deeper-tree one
  // (the more specific widget) — but keep the source of the one that has it.
  final byRect = <String, List<Map<String, dynamic>>>{};
  for (final r in out) {
    final rb = (r['r'] as Map).cast<String, dynamic>();
    final key = '\${(rb['x'] as num).toStringAsFixed(0)},\${(rb['y'] as num).toStringAsFixed(0)},\${(rb['w'] as num).toStringAsFixed(0)},\${(rb['h'] as num).toStringAsFixed(0)}';
    byRect.putIfAbsent(key, () => []).add(r);
  }
  final merged = <String, Map<String, dynamic>>{};
  for (final entry in byRect.entries) {
    final list = entry.value;
    if (list.length == 1) {
      merged[entry.key] = list.first;
      continue;
    }
    // Deepest in the tree = smallest 'd' value recorded last… keep the LAST
    // (deepest) that carries a source position, else the smallest.
    Map<String, dynamic> best = list.first;
    for (final r in list) {
      final hasSrc = r.containsKey('file');
      final bestHasSrc = best.containsKey('file');
      if (hasSrc && !bestHasSrc) {
        best = r;
      } else if (hasSrc == bestHasSrc) {
        final d = (r['d'] as int) ~/ 1;
        final bd = (best['d'] as int) ~/ 1;
        // Larger depth = more specific.
        if (d > bd) best = r;
      }
    }
    // A full-screen frame should not cover the whole app: drop regions that
    // are >= 96% of the screen (the root scaffold etc.).
    final rb = (best['r'] as Map).cast<String, dynamic>();
    final w = (rb['w'] as num).toDouble();
    final h = (rb['h'] as num).toDouble();
    if (w * h >= 0.96 * 1280 * 800) continue;
    merged[entry.key] = best;
  }
  return merged.values.toList()
    ..sort((a, b) => ((a['d'] as int) - (b['d'] as int)));
}

String _hex(ui.Color c) =>
    '#\${(c.value & 0xFFFFFF).toRadixString(16).padLeft(6, '0').toUpperCase()}';

/// Sample the raw RGBA [raw] (w×h, row-major) over the rect and return the
/// most common (mode) colour as #RRGGBB — for a solid region this is the
/// painted background; text glyphs / anti-aliased edges are a minority of the
/// samples so the background wins. Returns null if nothing sampleable.
String? _modeColor(
    List<int> raw, int w, int h, double x, double y, double rw, double rh) {
  if (raw.isEmpty || w <= 0 || h <= 0 || rw < 4 || rh < 4) return null;
  final counts = <int, int>{};
  int total = 0;
  void add(int px, int py) {
    if (px < 0 || py < 0 || px >= w || py >= h) return;
    final i = (py * w + px) * 4;
    if (i + 3 >= raw.length) return;
    // Skip fully-transparent pixels (not painted).
    if (raw[i + 3] < 200) return;
    final key = (raw[i] << 16) | (raw[i + 1] << 8) | raw[i + 2];
    counts[key] = (counts[key] ?? 0) + 1;
    total++;
  }
  // Sample a small grid across the region (capped), dense enough that a solid
  // fill dominates the mode, sparse enough to stay fast.
  final cols = (rw / 12).clamp(1, 6).round();
  final rows = (rh / 12).clamp(1, 6).round();
  for (var r = 0; r < rows; r++) {
    for (var c = 0; c < cols; c++) {
      final px = (x + rw * (c + 0.5) / cols).round();
      final py = (y + rh * (r + 0.5) / rows).round();
      add(px, py);
    }
  }
  if (total == 0) return null;
  int bestKey = 0;
  var bestCount = 0;
  counts.forEach((k, c) {
    if (c > bestCount) {
      bestCount = c;
      bestKey = k;
    }
  });
  // Require a clear majority; otherwise the region is busy (mixed) and a
  // single colour would be misleading.
  if (bestCount * 2 < total) return null;
  final r = (bestKey >> 16) & 0xFF;
  final g = (bestKey >> 8) & 0xFF;
  final b = bestKey & 0xFF;
  return '#'
      '\${r.toRadixString(16).padLeft(2, '0').toUpperCase()}'
      '\${g.toRadixString(16).padLeft(2, '0').toUpperCase()}'
      '\${b.toRadixString(16).padLeft(2, '0').toUpperCase()}';
}

String _slug(String s) =>
    s.toLowerCase().replaceAll(RegExp(r'[^a-z0-9]+'), '_').replaceAll(RegExp(r'^_+|_+\$'), '');

String _labelFor(String type) {
  if (type.contains('RenderParagraph')) return 'Text';
  if (type.contains('RenderDecoratedBox')) return 'Box';
  if (type.contains('RenderImage')) return 'Image';
  if (type.contains('RenderClipRRect') || type.contains('RenderClipRect')) {
    return 'Card';
  }
  if (type.contains('RenderCustomPaint')) return 'Painted';
  if (type.contains('RenderLeaderAnnotation')) return 'Layer';
  return type.replaceAll('Render', '');
}

/// Mock the method channels of the plugins generated apps commonly use, so
/// `main()` initialisation (SharedPreferences.getInstance() etc.) can't hang
/// the harness in the test environment.
void _mockCommonPlugins() {
  final messenger =
      TestDefaultBinaryMessengerBinding.instance.defaultBinaryMessenger;
  messenger.setMockMethodCallHandler(
    const MethodChannel('plugins.flutter.io/shared_preferences'),
    (call) async {
      switch (call.method) {
        case 'getAll':
          return <String, Object>{};
        case 'containsKey':
          return false;
        default:
          return null;
      }
    },
  );
  messenger.setMockMethodCallHandler(
    const MethodChannel('plugins.flutter.io/path_provider'),
    (call) async => Directory.systemTemp.path,
  );
  messenger.setMockMethodCallHandler(
    const MethodChannel('plugins.flutter.io/url_launcher'),
    (call) async => false,
  );
  messenger.setMockMethodCallHandler(
    const MethodChannel('dev.fluttercommunity.plus/package_info'),
    (call) async => null,
  );
}
''';
}

String _esc(String s) =>
    s.replaceAll(r'\', r'\\').replaceAll("'", r"\'");

/// Extract named routes from a generated `app_routes.dart` source. Returns the
/// route keys in declaration order (home excluded — it's always visited first
/// from whatever `home:` is).
List<String> parseNamedRoutes(String appRoutesSource) {
  final routes = <String>[];
  final re = RegExp(r"""['\"](/[^'\"]*)['\"]\s*:""");
  for (final m in re.allMatches(appRoutesSource)) {
    final name = m.group(1)!;
    if (!routes.contains(name)) routes.add(name);
  }
  return routes;
}

/// Read a `name:` from pubspec source.
String? parsePubspecName(String pubspecSource) {
  final m = RegExp(r'^name:\s*([A-Za-z0-9_]+)', multiLine: true)
      .firstMatch(pubspecSource);
  return m?.group(1);
}
